paths:
    sets:       'data/sets.csv'
    workouts:   'data/workouts.csv'
    weight:     'data/weight.csv'
    exercises:  'data/exercises.csv'
    cardio:     'data/cardio.csv'
    kettlebell: 'data/kettlebell.csv'
    imports:    'data/imports.csv'
    ocr_notes:  'data/ocr_notes.csv'

training_max:
  S00: 116
  H00.0: 141
  P10.0: 57
  P01.00: 91
